"""añadida clave foranea

Revision ID: 1f0080810a34
Revises: b6e434e1483a
Create Date: 2025-05-16 11:20:52.029073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f0080810a34'
down_revision: Union[str, None] = 'b6e434e1483a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paciente', sa.Column('medico_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'paciente', 'medico', ['medico_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paciente', type_='foreignkey')
    op.drop_column('paciente', 'medico_id')
    # ### end Alembic commands ###
