"""creada tabla paciente

Revision ID: b6e434e1483a
Revises: 6d2413271159
Create Date: 2025-05-16 10:58:47.640050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e434e1483a'
down_revision: Union[str, None] = '6d2413271159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=True),
    sa.Column('apellido', sa.String(length=60), nullable=True),
    sa.Column('Tipo_de_documento', sa.String(length=60), nullable=True),
    sa.Column('numero_de_documento', sa.Integer(), nullable=True),
    sa.Column('telefono', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paciente')
    # ### end Alembic commands ###
